### ISSUE TITLE
Cant repeat hello world example

### ISSUE THREAD

**Issue by prog1dev** [Authorea/latexml-ruby#1]
I added `gem 'latexml-ruby'` to my Gemfile and tried to repeat example in pry console:

```
[1] pry(main)> require 'latexml'
=> true
[2] pry(main)> @latexml = LaTeXML.new
=> #<LaTeXML:0x007feae81d99a0
 @debug=true,
...
[3] pry(main)> response = @latexml.convert(literal: "hello world")
TypeError: no implicit conversion of nil into String
from /Users/ivan.filenko/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/latexml-ruby-0.0.2/lib/latexml.rb:250:in `system'
```
```
rails -v
Rails 4.1.8
ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin16.0]
rbenv -v
rbenv 1.1.0
bundle | grep latexml-ruby
Using latexml-ruby 0.0.2
bundle show latexml-ruby
/Users/ivan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/latexml-ruby-0.0.2
```
Same on `ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]` in irb session

**Comment by dginev** [comment]
Sounds like you need to install latexml on your system - the wrapper isn't self contained and currently has to shell-out into calling the latexml executables. [Installation instructions here](http://dlmf.nist.gov/LaTeXML/get.html). I thought this is detailed out in the readme, but it isn't - I'll outline it there.

I will also add a better error message here, as this is certainly very opaque.

**Comment by dginev** [comment]
Thanks for the issue report, I have updated the README and added a meaningful error + test:
28a40ffc7770f3d0019c88d1a7c9739b433c0cc7

Closing here for now, feel free to open new issues if some arise!
